
service: graphql-api

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  profile: ankith.aws.serverless.admin

functions:
  graphql:
    handler: handler.graphql
    events:
      - http:
          path: graphql
          method: post
  playground:
    handler: handler.playgroundHandler
    events:
    - http:
        path: playground
        method: get
        cors: true
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: 'yarn'   # Packager that will be used to package your external modules
  serverless-offline:
    port: 4000

